In [2]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [3]:
col = ['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH', 'sulphates','alcohol']
df = pd.read_csv('winequality-red.csv',sep=';')

In [4]:
df.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6

In [5]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [6]:
in_df = df.drop('quality',axis='columns')
in_df.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0

In [7]:
inputs = in_df.to_numpy()

In [8]:
inputs.astype('float32')

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]],
      dtype=float32)

In [9]:
re_list = [
'fixed acidity',	'volatile acidity',	'citric acid',	'residual sugar',	'chlorides',	'free sulfur dioxide',	'total sulfur dioxide',	'density'	,'pH'	,'sulphates',	'alcohol']
tar_df = df.drop(re_list,axis='columns')

In [10]:
targets = tar_df.to_numpy()
targets.astype('float32')

array([[5.],
       [5.],
       [5.],
       ...,
       [6.],
       [5.],
       [6.]], dtype=float32)

In [11]:
inputs = torch.tensor(inputs)
inputs =inputs.to(torch.float32)
targets = torch.tensor(targets)
targets =targets.to(torch.float32)
inputs.dtype

torch.float32

In [12]:
train_ds = TensorDataset(inputs,targets)
train_ds[0:3]

(tensor([[7.4000e+00, 7.0000e-01, 0.0000e+00, 1.9000e+00, 7.6000e-02, 1.1000e+01,
          3.4000e+01, 9.9780e-01, 3.5100e+00, 5.6000e-01, 9.4000e+00],
         [7.8000e+00, 8.8000e-01, 0.0000e+00, 2.6000e+00, 9.8000e-02, 2.5000e+01,
          6.7000e+01, 9.9680e-01, 3.2000e+00, 6.8000e-01, 9.8000e+00],
         [7.8000e+00, 7.6000e-01, 4.0000e-02, 2.3000e+00, 9.2000e-02, 1.5000e+01,
          5.4000e+01, 9.9700e-01, 3.2600e+00, 6.5000e-01, 9.8000e+00]]),
 tensor([[5.],
         [5.],
         [5.]]))

In [13]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [14]:
inputs.shape

torch.Size([1599, 11])

In [15]:
for wei , bia in train_dl:
    print(wei)
    print(bia)
    break

tensor([[ 6.8000,  0.3600,  0.3200,  1.8000,  0.0670,  4.0000,  8.0000,  0.9928,
          3.3600,  0.5500, 12.8000],
        [ 8.8000,  0.6000,  0.2900,  2.2000,  0.0980,  5.0000, 15.0000,  0.9988,
          3.3600,  0.4900,  9.1000],
        [ 9.4000,  0.3300,  0.5900,  2.8000,  0.0790,  9.0000, 30.0000,  0.9976,
          3.1200,  0.5400, 12.0000],
        [ 8.4000,  0.6200,  0.1200,  1.8000,  0.0720, 38.0000, 46.0000,  0.9950,
          3.3800,  0.8900, 11.8000],
        [ 6.1000,  0.4000,  0.1600,  1.8000,  0.0690, 11.0000, 25.0000,  0.9955,
          3.4200,  0.7400, 10.1000]])
tensor([[7.],
        [5.],
        [6.],
        [6.],
        [7.]])


In [16]:
model = nn.Linear(11,1)
print(model.weight)
print(model.bias)
model.bias.dtype


Parameter containing:
tensor([[-0.1920, -0.0562,  0.1727,  0.0018,  0.2326,  0.0326,  0.2019,  0.0725,
          0.2400,  0.1217,  0.1053]], requires_grad=True)
Parameter containing:
tensor([0.0975], requires_grad=True)


torch.float32

In [17]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.1920, -0.0562,  0.1727,  0.0018,  0.2326,  0.0326,  0.2019,  0.0725,
           0.2400,  0.1217,  0.1053]], requires_grad=True),
 Parameter containing:
 tensor([0.0975], requires_grad=True)]

In [18]:
predict = model(inputs)
predict

tensor([[ 7.8534],
        [14.8728],
        [11.9451],
        ...,
        [10.0665],
        [10.9853],
        [10.2210]], grad_fn=<AddmmBackward0>)

In [19]:
import torch.nn.functional as f

In [20]:
loss_fn = f.mse_loss

In [21]:
loss = loss_fn(model(inputs),targets)
print(loss)

tensor(73.6896, grad_fn=<MseLossBackward0>)


In [22]:
opt = torch.optim.SGD(model.parameters(),lr=1e-5)

In [23]:
def fit(num_epochs,model,loss_fn,opt,train_dl):
    for epoch in range(num_epochs):
        for inps ,targ in train_dl:
            predict = model(inps)

            loss = loss_fn(predict,targ)

            loss.backward()

            opt.step()

            opt.zero_grad()
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1,num_epochs,loss.item()))

In [24]:
fit(170,model,loss_fn,opt,train_dl)

Epoch [10/170], Loss: 0.7412
Epoch [20/170], Loss: 0.1862
Epoch [30/170], Loss: 0.1950
Epoch [40/170], Loss: 0.4621
Epoch [50/170], Loss: 0.1138
Epoch [60/170], Loss: 0.2824
Epoch [70/170], Loss: 0.2835
Epoch [80/170], Loss: 1.4631
Epoch [90/170], Loss: 1.1528
Epoch [100/170], Loss: 0.2357
Epoch [110/170], Loss: 0.0662
Epoch [120/170], Loss: 0.0985
Epoch [130/170], Loss: 0.7576
Epoch [140/170], Loss: 0.1215
Epoch [150/170], Loss: 2.1807
Epoch [160/170], Loss: 0.4591
Epoch [170/170], Loss: 0.3364


In [25]:
targets

tensor([[5.],
        [5.],
        [5.],
        ...,
        [6.],
        [5.],
        [6.]])

In [26]:
predict = model(inputs)
predict

tensor([[5.2195],
        [5.3247],
        [5.3138],
        ...,
        [5.8634],
        [5.5906],
        [5.8140]], grad_fn=<AddmmBackward0>)

In [29]:
inps = torch.tensor([[8.5	,0.28	,0.56	,1.8	,0.092	,35	,103	,0.9969	,3.3	,0.75	,10.5]])
inps = inps.to(torch.float32)
res = model(inps)
res = res.item()
print('Quality of input wine is : ',res)

Quality of input wine is :  5.801763534545898


8.5;0.28;0.56;1.8;0.092;35;103;0.9969;3.3;0.75;10.5;7
